package gui;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import model.component.LiMoZak;
import model.component.AidZakInfo;
import model.sluzby.IntZakaznikService;
import model.sluzby.ZakaznikDbService;

/**
 *
 * @author notme159
 */
public class DiaPridPerm extends javax.swing.JDialog {

    private IntZakaznikService zakaznikService;
    private List<AidZakInfo> lstZakaznici;
    private LiMoZak mdlZakaznici;
    private double cena;
    private String[] permInfo = new String[5];

    public DiaPridPerm(JFrame owner, boolean modal) {
        super(owner, modal);
        setTitle("Přidat permanentku");

        zakaznikService = new ZakaznikDbService();

        lstZakaznici = new ArrayList<>();
        lstZakaznici = zakaznikService.prehledZak();
        mdlZakaznici = new LiMoZak(lstZakaznici);

        initComponents();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pack();
        setLocationRelativeTo(owner);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstZak = new javax.swing.JList();
        chTyp = new javax.swing.JComboBox();
        lblCena = new javax.swing.JLabel();
        cbCasova = new javax.swing.JComboBox();
        cbBodova = new javax.swing.JComboBox();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        lblNadpis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lstZak.setModel(mdlZakaznici);
        lstZak.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        lstZak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstZakMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstZak);

        chTyp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Zvolte typ...", "Časová", "Bodová" }));
        chTyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chTypActionPerformed(evt);
            }
        });

        lblCena.setBackground(new java.awt.Color(255, 255, 255));
        lblCena.setText("Cena: ");

        cbCasova.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Zvolte typ...", "2 hodiny", "4 hodiny", "celý den" }));
        cbCasova.setEnabled(false);
        cbCasova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCasovaActionPerformed(evt);
            }
        });

        cbBodova.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Zvolte typ...", "120b", "200b", "350b" }));
        cbBodova.setEnabled(false);
        cbBodova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBodovaActionPerformed(evt);
            }
        });

        btOk.setBackground(new java.awt.Color(255, 255, 255));
        btOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/img/ok.jpg"))); // NOI18N
        btOk.setEnabled(false);
        btOk.setMaximumSize(new java.awt.Dimension(52, 52));
        btOk.setMinimumSize(new java.awt.Dimension(50, 50));
        btOk.setPreferredSize(new java.awt.Dimension(51, 51));
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        lblNadpis.setBackground(new java.awt.Color(255, 255, 255));
        lblNadpis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNadpis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNadpis.setText("Přidání nové permanentky");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNadpis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chTyp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbCasova, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbBodova, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                        .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(lblCena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblNadpis, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chTyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCena, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbCasova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbBodova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chTypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chTypActionPerformed
        if (chTyp.getSelectedItem() == "Časová") {
            cbCasova.setEnabled(true);
            cbBodova.setEnabled(false);
            permInfo[2] = (String) chTyp.getSelectedItem();
        } else if (chTyp.getSelectedItem() == "Bodová") {
            cbCasova.setEnabled(false);
            cbBodova.setEnabled(true);
            permInfo[2] = (String) chTyp.getSelectedItem();
        }
        if (permInfo[0] != null && permInfo[1] != null && permInfo[2] != null) {
            btOk.setEnabled(true);
        } else {
            btOk.setEnabled(false);
        }

    }//GEN-LAST:event_chTypActionPerformed

    private void cbCasovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCasovaActionPerformed
        if (cbCasova.getSelectedItem() == "2 hodiny") {
            cena = 270;
        } else if (cbCasova.getSelectedItem() == "4 hodiny") {
            cena = 370;
        } else if (cbCasova.getSelectedItem() == "celý den") {
            cena = 500;
        }
        lblCena.setText("Cena: " + cena);
        permInfo[1] = String.valueOf(cena);
        if (permInfo[0] != null && permInfo[1] != null && permInfo[2] != null) {
            btOk.setEnabled(true);
        } else {
            btOk.setEnabled(false);
        }
    }//GEN-LAST:event_cbCasovaActionPerformed

    private void cbBodovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBodovaActionPerformed
        if (cbBodova.getSelectedItem() == "120b") {
            cena = 220;
        } else if (cbBodova.getSelectedItem() == "200b") {
            cena = 320;
        } else if (cbBodova.getSelectedItem() == "350b") {
            cena = 400;
        }
        lblCena.setText("Cena: " + cena);
        permInfo[1] = String.valueOf(cena);
        if (permInfo[0] != null && permInfo[1] != null && permInfo[2] != null) {
            btOk.setEnabled(true);
        } else {
            btOk.setEnabled(false);
        }
    }//GEN-LAST:event_cbBodovaActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        zakaznikService.pridatPerm(permInfo);
        JOptionPane.showMessageDialog(null, "Permanentka přidána");
        setVisible(false);
    }//GEN-LAST:event_btOkActionPerformed

    private void lstZakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstZakMouseClicked
        permInfo = ziskejInfoZJListZak();
        System.out.println(permInfo[0] + "\n" + permInfo[1] + "\n" + permInfo[2]);
        if (permInfo[0] != null && permInfo[1] != null && permInfo[2] != null) {
            btOk.setEnabled(true);
        } else {
            btOk.setEnabled(false);
        }

    }//GEN-LAST:event_lstZakMouseClicked

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btCancelActionPerformed

    private String[] ziskejInfoZJListZak() {
        if (lstZak.getSelectedValue() != null) {
            String stringZakId = (String) lstZak.getSelectedValue();
            String[] rozdeleni = stringZakId.split(" ");
            permInfo[0] = rozdeleni[0];
            return permInfo;
        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOk;
    private javax.swing.JComboBox cbBodova;
    private javax.swing.JComboBox cbCasova;
    private javax.swing.JComboBox chTyp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCena;
    private javax.swing.JLabel lblNadpis;
    private javax.swing.JList lstZak;
    // End of variables declaration//GEN-END:variables
}
