package gui;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.component.LiMoProd;
import model.component.AidProdInfo;
import model.component.AidVypInfo;
import model.component.TaMoProd;
import model.component.TaMoZakSimple;
import model.component.AidZakInfo;
import model.component.TaMoZakVyp;
import model.entity.Produkt;
import model.entity.Zakaznik;
import model.sluzby.IntZakaznikService;
import model.sluzby.ZakaznikDbService;

public class DiaSpravaVyp extends javax.swing.JDialog {

    private IntZakaznikService zakaznikService;
    private List<AidProdInfo> prodInfa;
    private TaMoProd tblModelProdukty;
    private List<Zakaznik> zakaznici = new ArrayList<>();
    private TaMoZakSimple tblModelZak;
    private List<Produkt> produktyPridane = new ArrayList<>();
    private LiMoProd lstModelProdukty;
    private List<AidVypInfo> vypInfa;
    private TaMoZakVyp tblModelZakVyp;
    private String vypId;
    private int prodId;
    private String zakJm;
    private String zakPrij;
    private Double celkovaCena = 0.0;
    private boolean vracenoVcas = true;

    public DiaSpravaVyp(JFrame owner, boolean modal) {
        super(owner, modal);
        setTitle("Správa výpůjček");

        zakaznikService = new ZakaznikDbService();
        prodInfa = zakaznikService.getProdukty();

        tblModelProdukty = new TaMoProd(prodInfa);

        // getnu z inf aktualni zakazniky, nic vic me nezajima
        List<AidZakInfo> zakInfa = zakaznikService.prehledZak();
        for (AidZakInfo zakInfo : zakInfa) {
            zakaznici.add(zakInfo.getZak());
        }

        tblModelZak = new TaMoZakSimple(zakaznici);

        lstModelProdukty = new LiMoProd(produktyPridane);
        
        vypInfa = zakaznikService.getVypInfa();

        tblModelZakVyp = new TaMoZakVyp(vypInfa);

        initComponents();
        pack();
        setLocationRelativeTo(owner);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTaProd = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTaZak = new javax.swing.JTable();
        jlbZakId = new javax.swing.JLabel();
        tfZakId = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlProdukty = new javax.swing.JList();
        btPridProdDoList = new javax.swing.JButton();
        btVytVyp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jxdOd = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jxdDo = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        tfCelkCen = new javax.swing.JTextField();
        btSpocAZval = new javax.swing.JButton();
        tfZakJm = new javax.swing.JTextField();
        tfZakPrij = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTaZakVyp = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btVraceno = new javax.swing.JButton();
        cbVracenoVcas = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTaProd.setModel(tblModelProdukty);
        jTaProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTaProdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTaProd);

        jTaZak.setModel(tblModelZak);
        jTaZak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTaZakMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTaZak);

        jlbZakId.setText("ID:");

        tfZakId.setEditable(false);

        jlProdukty.setModel(lstModelProdukty);
        jScrollPane3.setViewportView(jlProdukty);

        btPridProdDoList.setText("Přidat");
        btPridProdDoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPridProdDoListActionPerformed(evt);
            }
        });

        btVytVyp.setText("Vytvoř Výpůjčku");
        btVytVyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVytVypActionPerformed(evt);
            }
        });

        jLabel1.setText("Od:");

        jLabel2.setText("Do:");

        jLabel3.setText("Celková Cena:");

        btSpocAZval.setText("Spočti a zvaliduj");
        btSpocAZval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSpocAZvalActionPerformed(evt);
            }
        });

        tfZakJm.setEditable(false);
        tfZakJm.setText(" ");

        tfZakPrij.setEditable(false);
        tfZakPrij.setText(" ");

        jLabel4.setText("Příjmení:");

        jLabel5.setText("Jméno:");

        jTaZakVyp.setModel(tblModelZakVyp);
        jScrollPane4.setViewportView(jTaZakVyp);

        jLabel6.setText("Přehled zákazníků s výpůjčkou:");

        jLabel7.setText("Přehled produktů:");

        jLabel8.setText("Přehled zákazníků:");

        btVraceno.setBackground(new java.awt.Color(255, 255, 255));
        btVraceno.setText("Vrátit");
        btVraceno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVracenoActionPerformed(evt);
            }
        });

        cbVracenoVcas.setBackground(new java.awt.Color(255, 255, 255));
        cbVracenoVcas.setText("Vráceno včas");

        jLabel9.setText("ID:");

        jLabel10.setText("Název:");

        jLabel11.setText("Název:");

        jLabel12.setText("Velikost:");

        jLabel13.setText("Cena:");

        jLabel14.setText("Půjčeno:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btPridProdDoList))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btSpocAZval, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlbZakId)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfZakId, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jxdOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jxdDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(11, 11, 11)
                                        .addComponent(tfZakJm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfZakPrij, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(31, 31, 31)
                                        .addComponent(tfCelkCen, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btVytVyp)))
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(323, 323, 323))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(447, 447, 447)
                        .addComponent(btVraceno)
                        .addGap(18, 18, 18)
                        .addComponent(cbVracenoVcas))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1084, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbZakId)
                    .addComponent(tfZakId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPridProdDoList)
                    .addComponent(tfZakJm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfZakPrij, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jxdOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jxdDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addGap(26, 26, 26)
                        .addComponent(btSpocAZval)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfCelkCen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btVytVyp))))
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVraceno)
                    .addComponent(cbVracenoVcas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPridProdDoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPridProdDoListActionPerformed

        int row = jTaProd.getSelectedRow();

        Produkt p = null;

        if (row != -1) {

            prodId = (int) jTaProd.getModel().getValueAt(row, 0);

            for (AidProdInfo aidProdInfo : prodInfa) {
                if (aidProdInfo.getProd().getProdukt_id() == prodId) {
                    p = aidProdInfo.getProd();
                }
            }

            if (!p.isPujceno()) {

                if (!produktyPridane.isEmpty()) {
                    for (int i = 0; i < produktyPridane.size(); i++) {
                        if (produktyPridane.contains(p)) {
                            JOptionPane.showMessageDialog(this, "Produkt již přidán!", "Chyba", JOptionPane.ERROR_MESSAGE);
                            break;
                        } else {
                            produktyPridane.add(p);
                            lstModelProdukty.fireModelChanged();
                            break;
                        }
                    }
                } else {
                    produktyPridane.add(p);
                    lstModelProdukty.fireModelChanged();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Produkt již vypůjčen!", "Chyba", JOptionPane.ERROR_MESSAGE);
            }
        }

        

    }//GEN-LAST:event_btPridProdDoListActionPerformed

    private void btVytVypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVytVypActionPerformed
        zakaznikService.vytvVyp(jxdOd.getDate(), jxdDo.getDate(), celkovaCena, tfZakId.getText().trim(), produktyPridane);
        tblModelZakVyp.fireTableDataChanged();
        JOptionPane.showMessageDialog(this, "Výpůjčka vytvořena.");
        vypInfa = zakaznikService.getVypInfa();
        tblModelZakVyp.update(vypInfa);
        prodInfa = zakaznikService.getProdukty();
        tblModelProdukty.update(prodInfa);

    }//GEN-LAST:event_btVytVypActionPerformed

    private void jTaZakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTaZakMouseClicked
        int row = jTaZak.getSelectedRow();

        if (row != -1) {
            vypId = String.valueOf(jTaZak.getModel().getValueAt(row, 0));
            tfZakId.setText(vypId);
            zakJm = String.valueOf(jTaZak.getModel().getValueAt(row, 1));
            tfZakJm.setText(zakJm);
            zakPrij = String.valueOf(jTaZak.getModel().getValueAt(row, 2));
            tfZakPrij.setText(zakPrij);

        }
    }//GEN-LAST:event_jTaZakMouseClicked

    private void btSpocAZvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSpocAZvalActionPerformed
        int pocetDni = spoctiDobuPujc();

        for (Produkt p : produktyPridane) {
            p.getCena();
            celkovaCena += pocetDni * p.getCena();
        }

        tfCelkCen.setText(celkovaCena + "");

    }//GEN-LAST:event_btSpocAZvalActionPerformed

    private void btVracenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVracenoActionPerformed

        int row = jTaZakVyp.getSelectedRow();

        if (row != -1) {
            // 3. sloupec, pocitani od nuly, je vypID
            vypId = String.valueOf(jTaZakVyp.getModel().getValueAt(row, 3));

            if (cbVracenoVcas.isSelected()) {
                zakaznikService.setVracenoVcas(true);
            } else {
                zakaznikService.setVracenoVcas(false);
            }

            zakaznikService.odstrVyp(Integer.parseInt(vypId.trim()));
        }

        prodInfa = zakaznikService.getProdukty();
        tblModelProdukty.update(prodInfa);

        vypInfa = zakaznikService.getVypInfa();
        tblModelZakVyp.update(vypInfa);
    }//GEN-LAST:event_btVracenoActionPerformed

    private void jTaProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTaProdMouseClicked
       int row = jTaProd.getSelectedRow();

        if (row != -1) {
            System.out.println(String.valueOf(jTaProd.getModel().getValueAt(row, 0)));
        }
    }//GEN-LAST:event_jTaProdMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPridProdDoList;
    private javax.swing.JButton btSpocAZval;
    private javax.swing.JButton btVraceno;
    private javax.swing.JButton btVytVyp;
    private javax.swing.JCheckBox cbVracenoVcas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTaProd;
    private javax.swing.JTable jTaZak;
    private javax.swing.JTable jTaZakVyp;
    private javax.swing.JList jlProdukty;
    private javax.swing.JLabel jlbZakId;
    private org.jdesktop.swingx.JXDatePicker jxdDo;
    private org.jdesktop.swingx.JXDatePicker jxdOd;
    private javax.swing.JTextField tfCelkCen;
    private javax.swing.JTextField tfZakId;
    private javax.swing.JTextField tfZakJm;
    private javax.swing.JTextField tfZakPrij;
    // End of variables declaration//GEN-END:variables

    private int spoctiDobuPujc() {
        long from = jxdOd.getDateInMillis();
        long to = jxdDo.getDateInMillis();
        long diff = (to - from) / 1000 / 60 / 60 / 24;
        return (int) diff + 1;
    }
}
